### ISSUE TITLE
CRT not loaded at first powerup

### ISSUE THREAD

**Issue by SanguineBrah** [vossstef/tang_nano_20k_c64#81] opened 2024-07-28 09:47 UTC
On first boot, c64crt.crt shows as loaded in the Storage menu but it isn't loaded in the core. The Reset option doesn't fix it but using the Cold Boot option then successfully loads the default cartridge.

I am testing using the CBM kernal and the [Epyx fastload cartridge](https://rr.pokefinder.org/wiki/Epyx_FastLoad) (FASTLOAD should show after the READY prompt).

**Comment by vossstef** [comment] 2024-10-18 18:22
Multiload CRT got once again broken...

**Comment by vossstef** [comment] 2024-10-18 18:40
I just created a new release that corrects the problem. 
Pls try and report. thx

**Comment by SanguineBrah** [comment] 2024-10-18 19:00
I'm seeing the same behaviour in the latest release. On first boot, the default cartridge is not loaded. It still isn't loaded on using the reset option but using the cold boot option in the menu then loads the cartridge correctly. The cartridge is also loaded correctly if I select it from the menu.

**Comment by vossstef** [comment] 2024-10-18 20:35
@SanguineBrah, confirmed! 
Looks like that also normal CRT load via SD card after power-up got broken. 
It works if you load normally after power op via OSD.

**Comment by vossstef** [comment] 2024-10-18 22:48
@SanguineBrah, after extensive testing i figured out that the power-up CRT load issue is not present with the misterynano fw.
I updated misterynano with latest c64 and vic20 core OSD needs and added the .bin and cfg to the release also.
Would be great if you will find time to test that and please let me know.

**Comment by SanguineBrah** [comment] 2024-10-19 06:49
@vossstef I can confirm that the misterynano firmware in the new release fixes this issue for me. Cartridges are now loading immediately on first boot and behaving correctly.

**Comment by harbaum** [comment] 2024-10-19 08:05
Please feel free to do Companion releases yourself. If this temporarily  breaks another core then this will just be fixed asap.

**Comment by vossstef** [comment] 2024-10-19 08:06
great!
Now need i to find out and fix for companion.

**Comment by vossstef** [comment] 2024-10-19 20:26
@SanguineBrah,
i created a 1.6.0 pre-release supporting apart from proper Multcard load also a freeze function with e.g. Action Replay CRT.
Not sure is Epyx fastload also supporting freeze but feel free...

**Comment by vossstef** [comment] 2024-10-20 16:17
CRT issues fixed in release v1.6.1

**Closed by vossstef** 2024-10-20 16:17 UTC
Labels: bug
